baseURL = 'https://sfcriticalmass.com/'
languageCode = 'en-us'
title = 'SF Critical Mass'
theme = 'ananke'
copyright = 'Contributors, MIT License'

[params.ananke.social.follow]
new_window_icon = false
networks = [
#    "twitter",
    "bluesky",
    "mastodon",
    "instagram",
    "facebook",
]

[params.ananke.social.twitter]
username = "CriticalMassSF"

[params.ananke.social.instagram]
username = "sfcriticalmass"

[params.ananke.social.facebook]
username = "criticalmasssf"

[params.ananke.social.mastodon]
profilelink = "https://sfba.social/@sfcriticalmass"

[params.ananke.social.bluesky]
profilelink = "https://sfcriticalmass.bsky.social"
